CREATE TABLE IF NOT EXISTS tasks (
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  author VARCHAR(255) NOT NULL,
  priority INTEGER NOT NULL,
  rate DOUBLE PRECISION NOT NULL,
  complete BOOLEAN NOT NULL
);
